version: '3'
services:
  trial-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20774:20774"
    networks:
      - net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgres/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - net

volumes:
  postgres:
    driver: local

networks:
  net:
